### ISSUE TITLE
[PATCH] fix POD ERRORS

### ISSUE THREAD

**Issue by gregoa** [ingydotnet/alt-pm#1]
In Debian we are currently applying the following patch to Alt.
We thought you might be interested in it too.

Description: fix POD ERRORS
Origin: vendor
Author: gregor herrmann gregoa@debian.org
Applied-Upstream: **\* FIXME ***

The patch is tracked in our Git repository at
http://anonscm.debian.org/gitweb/?p=pkg-perl/packages/libalt-perl.git;a=blob;f=debian/patches/pod-syntax.patch;hb=HEAD

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by dolmen** [comment]
:+1:
The `=encoding` is still missing in 0.09 as can be seen on MetaCPAN.

**Comment by ingydotnet** [comment]
Fixed in Alt-0.10. Thanks!

**Comment by gregoa** [comment]
On Thu, 31 Jul 2014 10:41:16 -0700, Ingy döt Net wrote:

> Fixed in Alt-0.10. Thanks!

Thanks.
Maybe you could also look into
https://github.com/ingydotnet/xxx-pm/issues/4
while your fixing your POD :)

Cheers,
gregor

## 

 .''`.  Homepage: http://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer  -  http://www.debian.org/
`. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
`\-   NP: The Doors: Riders On The Storm

**Comment by ingydotnet** [comment]
Thanks. This turned out to be a bug triggered by modules with 3 or less
characters in their name! Fixed in Zilla-Dist, then just re-released the
affected modules.

**Comment by gregoa** [comment]
On Thu, 31 Jul 2014 12:13:47 -0700, Ingy döt Net wrote:

> Thanks. This turned out to be a bug triggered by modules with 3 or less
> characters in their name! Fixed in Zilla-Dist, then just re-released the
> affected modules.

Heh, nice.
Glad you found it.

Cheers,
gregor

## 

 .''`.  Homepage: http://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer  -  http://www.debian.org/
`. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
`\-   NP: Beatles
